{% set name = "rdkit-to-params" %}
{% set version = "1.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdkit_to_params-{{ version }}.tar.gz
  sha256: 5a8130e00da3a55365c950fa4324eb5f622797078add5340bea0a3d130f4b787

build:
  entry_points:
    - smiles-to-params=rdkit_to_params.cli:smiles
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - rdkit

test:
  imports:
    - rdkit_to_params
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matteoferla/rdkit_to_params
  summary: Create or modify Rosetta params files (topology files) from scratch, RDKit mols or another params file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
