{% set name = "rdkit-to-params" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdkit_to_params-{{ version }}.tar.gz
  sha256: 42f254c406f2a047537d146e5420d0d2334abcdb9deebc5cf18dabd0d7d51848

build:
  entry_points:
    - smiles-to-params=rdkit_to_params.cli:smiles
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rdkit

test:
  imports:
    - rdkit_to_params
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matteoferla/rdkit_to_params
  summary: Create or modify Rosetta params files (topology files) from scratch, RDKit mols or another params file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
